FROM python:3.13-slim
WORKDIR /app

# 1. 只复制依赖描述文件（这些文件很少变）
COPY requirements.txt ./
COPY whl/ ./whl/

# 2. 安装依赖（只要 requirements.txt 不变，这层永远用缓存）
RUN pip install --no-cache-dir -r requirements.txt -i https://pypi.tuna.tsinghua.edu.cn/simple

# 3. 安装本地的 wheel 包
RUN pip install --no-cache-dir whl/*.whl

# 4. 复制源代码
COPY . .

# 将当前项目安装为包，生成全局可执行的 ruoyi 命令。
RUN pip install --no-cache-dir .


# 暴露端口
EXPOSE 9099

# 启动命令
CMD ["ruoyi", "app", "run", "--env=dockermy"]
