[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "pgt"
dynamic = ["version"]
description = "PayloadGroundTest backend internal CLI entrypoint"
requires-python = ">=3.13"

[project.scripts]
ruoyi = "cli.main:main"

[tool.setuptools.packages.find]
include = ["cli*"]

[tool.setuptools.dynamic]
version = { attr = "version.appVersion" }
